kind: pipeline
name: Nepmia.fr auto update

pipeline:
  update_site:
    image: appleboy/drone-ssh
    host: nepmia.design
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    script:
    - cd scripts
    - bash clone.sh